# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d9cbfb7bdeef70c4bbbadca5c97095535c3640b6387bb364e2d4cd3df692c4f89a5f32a6cbd8b4e67dfaeaad7ebbeec95a99df7b6cdcf0425a959cfb091161b

test:
  secret_key_base: 779822a10908dd5785a9053a89cde58b4a3929fced0b3ece8d20c83b58c6d00da2b98d82bc42c77123bbd73ec789e53d6b4f5ef886f910cbe7a332424895da7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
